apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-logoutput
          emptyDir: {}
        - name: shared-pingpong
          persistentVolumeClaim:
            claimName: pingpong-pv-claim
      containers:
        - name: logoutput-write
          image: alago0/logoutput-write:7-28-2025-ver2
          volumeMounts:
            - name: shared-logoutput
              mountPath: /out/LogoutputShared
        - name: logoutput-read-api
          image: alago0/logoutput-read-api:7-28-2025-ver3
          volumeMounts:
            - name: shared-logoutput
              mountPath: /out/LogoutputShared
            - name: shared-pingpong
              mountPath: /out/PingpongShared
