apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-wwwroot
          emptyDir: {}
      containers:
        - name: logoutput-write
          image: alago0/logoutput-write:7-22-2025
          volumeMounts:
            - name: shared-wwwroot
              mountPath: /out/wwwroot
        - name: logouput-read-api
          image: alago0/logoutput-read-api:7-22-2025
          volumeMounts:
            - name: shared-wwwroot
              mountPath: /out/wwwroot
