# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stset
  namespace: project 
spec:
  serviceName: db-svc
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      labels:
        app: dbapp
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: todos
            - name: POSTGRES_USER
              value: todos
            - name: POSTGRES_PASSWORD
              value: todos
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              requests: 512Mi
              cpu: 200m 
      volumes:
        - name: init-scripts
          configMap:
            name: db-init
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 100Mi
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: project
  labels:
    app: db
spec:
  ports:
    - port: 5432
      name: db-port
  clusterIP: None
  selector:
    app: dbapp

---

# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
  namespace: project
data:
  01-create-todos-table.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      name VARCHAR(150)
    );
