apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-pingpong
          persistentVolumeClaim:
            claimName: pingpong-pv-claim
      containers:
        - name: logoutput
          image: alago0/pingpong:7-29-2025
          volumeMounts:
            - name: shared-pingpong
              mountPath: /out/PingpongShared
