apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: alago0/pingpong:9-9-2025-ver2
          volumeMounts:
          - name: pingpong-configmap-volume
            mountPath: /out/appsettings.json
            subPath: appsettings.json
      volumes:
        - name: pingpong-configmap-volume
          configMap:
            name: pingpong-configmap
