apiVersion: apps/v1
kind: Deployment
metadata:
  name: theproject 
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: theproject
  template:
    metadata:
      labels:
        app: theproject
    spec:
      volumes:
        - name: random-image
          persistentVolumeClaim:
            claimName: randomimage-claim
        - name: theproject-configmap-volume
          configMap:
            name: theproject-configmap
      containers:
        - name: theproject
          image: THEPROJECT/IMAGE
          volumeMounts:
          - name: random-image
            mountPath: /out/wwwroot/RandomPicture
          - name: theproject-configmap-volume
            mountPath: /out/appsettings.json
            subPath: appsettings.json
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              requests: 512Mi
              cpu: 200m 
