apiVersion: apps/v1
kind: Deployment
metadata:
  name: theproject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theproject
  template:
    metadata:
      labels:
        app: theproject
    spec:
      volumes:
        - name: random-image
          persistentVolumeClaim:
            claimName: randomimage-claim
      containers:
        - name: theproject
          image: alago0/theproject:8-8-2025-ver14
          volumeMounts:
          - name: random-image
            mountPath: /out/wwwroot/RandomPicture
