apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theproject-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-theproject-stripprefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /theproject
            pathType: Prefix
            backend:
              service:
                name: theproject-svc
                port:
                  number: 2347
