apiVersion: v1
kind: Service
metadata:
  name: theproject-svc
spec:
  type: NodePort
  selector:
    app: theproject
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 80 
