apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-pv-claim
  namespace: exercises
spec:
  storageClassName: pingpong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
