apiVersion: v1
kind: PersistentVolume
metadata:
  name: randomimage-pv
  namespace: project
spec:
  storageClassName: randomimage-pv
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/randomimage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
