apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cronjob-container
            image: alago0/todocronjob:8-30-2025
            env:
              - name: PG_USER
                value: todos
              - name: PG_PASS
                value: todos
              - name: PG_HOST
                value: db-svc:5432
              - name: PG_DB
                value: todos
          restartPolicy: OnFailure