apiVersion: v1
kind: Service
metadata:
  name: todobackend-svc
  namespace: project
spec:
  type: ClusterIP 
  selector:
    app: todobackend
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 80 
