name: Release project

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: alex-cluster
  GKE_ZONE: europe-central2-b
  REGISTRY: europe-central2-docker.pkg.dev
  REPOSITORY: gregistry
  
  PROJECT-IMAGE: project
  TODOBACKEND-IMAGE: todobackend
  
  SERIVICE: project
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deplooy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: 'Set Up Google Cloud Service Account'
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
          
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Get GKE Credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"

      - name: 'Form images names'
        run: |
          echo "PROJECT_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$PROJECT-IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "TODOBACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$TODOBACKEN-IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: 'Build and Push'
        run: |
          docker build ./theproject/TheProject -t $PROJECT_IMAGE_TAG
          docker push $PROJECT_IMAGE_TAG
          docker build ./theproject/TodoBackend -t $TODOBACKEND_IMAGE_TAG
          docker push $TODOBACKEND_IMAGE_TAG
