name: Delete namespace on branch delete

on:
  delete:
    types: [branch]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: alex-cluster
  GKE_ZONE: europe-central2-b
  
  BRANCH: ${{ github.ref_name }}

jobs:
  delete-k8s-namespace:
    name: Delete k8s namespace
    runs-on: ubuntu-latest
    environment: main
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: 'Set Up Google Cloud Service Account'
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
          
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Get GKE Credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      
      - name: 'Set target namespace'
        run: |
          if [[ "$BRANCH" == "main" ]] ; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=$BRANCH" >> $GITHUB_ENV
          fi
      
      - name: 'Delete namespace'
        run: kubectl delete namespace $NAMESPACE
      
